
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OtelbilgiSistemi.Data
{

using System;
    using System.Collections.Generic;
    
public partial class CalisanBilgi
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CalisanBilgi()
    {

        this.OtelKayits = new HashSet<OtelKayit>();

    }


    public int id { get; set; }

    public string calisanTC { get; set; }

    public string calisanAd { get; set; }

    public string calisanSoyad { get; set; }

    public string calisanTel { get; set; }

    public string calisanAdres { get; set; }

    public string calisanEPosta { get; set; }

    public string calisanDepartaman { get; set; }

    public string calisanPozisyon { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OtelKayit> OtelKayits { get; set; }

}

}
