

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OtelbilgiSistemi.Data
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class OtelBilgiEntities : DbContext
{
    public OtelBilgiEntities()
        : base("name=OtelBilgiEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<CalisanBilgi> CalisanBilgis { get; set; }

    public virtual DbSet<MusteriKayit> MusteriKayits { get; set; }

    public virtual DbSet<MusteriYorum> MusteriYorums { get; set; }

    public virtual DbSet<OtelKayit> OtelKayits { get; set; }

    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }

}

}

