
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OtelbilgiSistemi.Data
{

using System;
    using System.Collections.Generic;
    
public partial class MusteriYorum
{

    public int id { get; set; }

    public string musteriYorum1 { get; set; }

    public Nullable<int> currentMusteri { get; set; }



    public virtual OtelKayit OtelKayit { get; set; }

    public virtual MusteriKayit MusteriKayit { get; set; }

}

}
