
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OtelbilgiSistemi.Data
{

using System;
    using System.Collections.Generic;
    
public partial class MusteriKayit
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MusteriKayit()
    {

        this.MusteriYorums = new HashSet<MusteriYorum>();

    }


    public int id { get; set; }

    public string musteriTC { get; set; }

    public string musteriAd { get; set; }

    public string musteriSoyad { get; set; }

    public string musteriEPosta { get; set; }

    public string musteriTel { get; set; }

    public string musteriSifre { get; set; }

    public Nullable<int> isTrue { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MusteriYorum> MusteriYorums { get; set; }

}

}
